services:
  webapplication1:
    image: sleepysleepy8467/test:latest
    build:
      context: .
      dockerfile: src/WebApplication1/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    volumes:
      - ./work_schedule.db:/app/work_schedule.db
